export const PLACE_TYPES = {
    coffee: 'Coffee Shops',
    library: 'Libraries',
    bookstore: 'Bookstores',
    bar: 'Bars',
    gallery: 'Art Galleries',
    smoke_shop: 'Smoke Shops',
    thrift_store: 'Thrift Stores',
    cannabis_dispensary: 'Cannabis Dispensaries',
    night_club: 'Night Clubs',
    event_space: 'Event Spaces',
    skate_shop: 'Skate Shops',
    video_game_store: 'Video Game Stores',
    record_shop: 'Record Shops',
    tourist_attraction: 'Tourist Attractions',
    bodega: 'Bodegas',
    craft_fair: 'Craft Fairs',
    festival: 'Festivals',
    park: 'Parks',
    arcade: 'Arcades',
    skate_park: 'Skate Parks',
    farmers_market: 'Farmers Markets',
    taproom: 'Taprooms',
    casino: 'Casinos'
};

export const PLACE_TYPE_MAPPINGS = {
    coffee: ['cafe', 'coffee_shop'],
    library: ['library'],
    bookstore: ['book_store'],
    bar: ['bar', 'night_club'],
    gallery: ['art_gallery'],
    smoke_shop: ['tobacco_store'],
    thrift_store: ['store'],
    cannabis_dispensary: ['cannabis_store'],
    night_club: ['night_club'],
    event_space: ['event_venue'],
    skate_shop: ['store'],
    video_game_store: ['store'],
    record_shop: ['store'],
    tourist_attraction: ['tourist_attraction'],
    bodega: ['convenience_store', 'grocery_or_supermarket'],
    craft_fair: ['event_venue'],
    festival: ['event_venue'],
    park: ['park'],
    arcade: ['amusement_center'],
    skate_park: ['park'],
    farmers_market: ['market'],
    taproom: ['bar'],
    casino: ['casino']
};